export const assets = [
  { name: "intro-music", url: "audio/intro-music.mp3" },
  { name: "piano-sound", url: "audio/piano.mp3" },
  { name: "sine-wave", url: "audio/sine-wave.wav" },
  { name: "flower", url: "images/flower.png" },
  { name: "fund freq", url: "images/fund-freq.png" },
  { name: "piano", url: "images/piano.png" },
  { name: "robot", url: "images/robot.png" },
  { name: "sound wave", url: "images/sound-wave.png" },
  { name: "low sound", url: "audio/100hz.ogg" },
  { name: "high sound", url: "audio/800hz.ogg" },
  { name: "high wave", url: "images/high-freq.png" },
  { name: "low wave", url: "images/low-freq.png" },
  { name: "piano wave", url: "images/composite-wave.png" },
  { name: "robot wave", url: "images/robot-wave.png" },
  { name: "harm intro", url: "images/harmonic-intro.png" },
  { name: "some harms", url: "images/harmonics.svg" },
  { name: "harm series", url: "images/harmonic-series.svg" },
  { name: "scale", url: "images/scale-frequencies.svg" },
  { name: "piano keys", url: "images/piano-keys.svg" },
  { name: "first 32", url: "audio/first32.mp3" },
  { name: "first 16 harms", url: "images/first16harms.svg" },
  { name: "chrom scale", url: "images/chrom-scale.svg" },
  { name: "graph", url: "images/freq-pitch-rel.svg" },
  { name: "400 hz", url: "audio/400Hz.ogg" },
  { name: "450 hz", url: "audio/450Hz.ogg" },
  { name: "1000 hz", url: "audio/1000Hz.ogg" },
  { name: "1050 hz", url: "audio/1050Hz.ogg" },
  { name: "400 circ", url: "images/400hz.svg" },
  { name: "450 circ", url: "images/450hz.svg" },
  { name: "1000 circ", url: "images/1000hz.svg" },
  { name: "1050 circ", url: "images/1050hz.svg" },
  { name: "oboe vols", url: "images/oboe-vols.svg" },
  { name: "oboe 440", url: "audio/oboe440.wav" },
  { name: "oboe", url: "images/oboe.svg" },
  { name: "clarinet vols", url: "images/clarinet-vols.svg" },
  { name: "clarinet 440", url: "audio/clarinet440.wav" },
  { name: "clarinet", url: "images/clarinet.png" },
  { name: "guitar vols", url: "images/guitar-vols.svg" },
  { name: "guitar 440", url: "audio/guitar440.wav" },
  { name: "guitar", url: "images/guitar.svg" },
  { name: "piano vols", url: "images/piano-vols.svg" },
  { name: "note freqs", url: "images/note-freq.svg" },
  { name: "snare", url: "images/snare.png" },
  { name: "snare hit", url: "audio/snare.wav" },
  { name: "flower1", url: "images/flower1.png" },
  { name: "flower2", url: "images/flower2.png" },
  { name: "flower3", url: "images/flower3.png" },
  { name: "flower4", url: "images/flower4.png" },
  { name: "flower5", url: "images/flower5.png" },
  { name: "flower6", url: "images/flower6.png" },
  { name: "drumstick", url: "images/drumstick.svg" },
  { name: "credits", url: "images/credits.png" },
  {
    name: "Secular One",
    url: "https://fonts.googleapis.com/css2?family=Secular+One",
  },
  {
    name: "Mukta",
    url: "https://fonts.googleapis.com/css2?family=Mukta:wght@200;300;400;500;600;700;800",
  },
];
